name: sm_ai_support
description: A comprehensive Flutter package for integrating AI-powered customer support with real-time chat, media sharing, and multi-language support.
version: 1.0.5
homepage: https://github.com/sm-ai-sa/sm_ai_support
repository: https://github.com/sm-ai-sa/sm_ai_support
issue_tracker: https://github.com/sm-ai-sa/sm_ai_support/issues
documentation: https://github.com/sm-ai-sa/sm_ai_support/tree/main/docs

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #* Localizations
  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.7
  get_it: ^8.0.3
  cached_network_image: ^3.3.1
  uuid: ^4.3.3
  collection: ^1.18.0
  file_picker: ^9.0.2
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.0
  flutter_bloc: ^9.0.0
  modal_bottom_sheet: ^3.0.0
  gif: ^2.3.0
  intl: ^0.19.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.5
  path: ^1.9.0
  cached_video_player_plus: ^3.0.3
  flutter_xlider: ^3.5.0
  mime: ^2.0.0
  flutter_rating_stars: ^1.1.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.6.0
  open_filex: ^4.5.0
  video_player: ^2.9.2
  chewie: ^1.10.0
  flutter_cache_manager: ^3.4.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  socket_io_client: ^2.0.3+1
  uni_country_city_picker: ^1.0.2
  crypto: ^3.0.3
  http: ^1.2.2
  webview_flutter: ^4.9.0
  url_launcher: ^6.3.1
  lottie: ^3.1.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/category/
    - assets/icons/files/
    - assets/gif/
    - assets/fonts/
    - assets/lottie/
    - assets/fonts/hacen-maghreb/Hacen-Maghreb-Lt.ttf
    - assets/fonts/hacen-maghreb/Hacen-Maghreb-Bd.ttf


  fonts:
    - family: HacenMaghreb
      fonts:
        - asset: assets/fonts/hacen-maghreb/Hacen-Maghreb-Lt.ttf
          weight: 400
        - asset: assets/fonts/hacen-maghreb/Hacen-Maghreb-Bd.ttf
          weight: 500

    - family: DMSans
      fonts:
        - asset: assets/fonts/dm-sans/DMSans-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/dm-sans/DMSans-Light.ttf
          weight: 200
        - asset: assets/fonts/dm-sans/DMSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/dm-sans/DMSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/dm-sans/DMSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/dm-sans/DMSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/dm-sans/DMSans-ExtraBold.ttf
          weight: 700
